### ISSUE TITLE
Cannot build documentation - safe directory issue

### ISSUE THREAD

**Issue by pasglop** [JetBrains/writerside-github-action#1]
I tried to make Github Actions Build and deploy to work.

But on the Build step, I get the following error :
Seems related to https://github.com/actions/runner-images/issues/6775

2023-06-13 10:27:10,890 [   8380]   WARN - #git4idea.repo.GitUntrackedFilesHolder - detected dubious ownership in repository at '/github/workspace'
To add an exception for this directory, call:

git config --global --add safe.directory /github/workspace
com.intellij.openapi.vcs.VcsException: detected dubious ownership in repository at '/github/workspace'
To add an exception for this directory, call:

git config --global --add safe.directory /github/workspace
	at git4idea.commands.GitCommandResult.throwOnError(GitCommandResult.java:156)
	at git4idea.commands.GitCommandResult.getOutputOrThrow(GitCommandResult.java:145)
	at git4idea.index.GitIndexStatusUtilKt.getFileStatus(GitIndexStatusUtil.kt:84)
	at git4idea.repo.GitUntrackedFilesHolder.refreshFiles(GitUntrackedFilesHolder.java:351)
	at git4idea.repo.GitUntrackedFilesHolder.update(GitUntrackedFilesHolder.java:249)
	at com.intellij.util.ui.update.DisposableUpdate$1.doRun(DisposableUpdate.java:31)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:366)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:344)
	at com.intellij.util.ui.update.DisposableUpdate.run(DisposableUpdate.java:19)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:334)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:324)
	at com.intellij.util.ui.update.MergingUpdateQueue.doExecute(MergingUpdateQueue.java:281)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:264)
	at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:238)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:241)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:377)
	at com.intellij.util.Alarm$Request.run(Alarm.java:366)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:272)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:243)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:29)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.executeFirstTaskAndHelpQueue(BoundedTaskExecutor.java:216)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:2[12](https://github.com/pasglop/itineraire-touristique/actions/runs/5254282841/jobs/9492691486#step:4:13))
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:205)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1[13](https://github.com/pasglop/itineraire-touristique/actions/runs/5254282841/jobs/9492691486#step:4:14)6)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
JCEF(27:12:476): initialized stderr logger, severity=LOGSEVERITY_DISABLE
Exception in thread "Thread-123" java.lang.NullPointerException: Cannot invoke "java.awt.GraphicsConfiguration.createCompatibleVolatileImage(int, int, int)" because the return value of "javax.swing.JComponent.getGraphicsConfiguration()" is null
	at com.intellij.ui.jcef.JBCefOsrHandler.onPaint(JBCefOsrHandler.java:132)
	at jcef/org.cef.CefClient.onPaint(CefClient.java:865)
Exception in thread "Thread-152" java.lang.NullPointerException: Cannot invoke "java.awt.GraphicsConfiguration.createCompatibleVolatileImage(int, int, int)" because the return value of "javax.swing.JComponent.getGraphicsConfiguration()" is null
	at com.intellij.ui.jcef.JBCefOsrHandler.onPaint(JBCefOsrHandler.java:132)
	at jcef/org.cef.CefClient.onPaint(CefClient.java:865)
Open solution: ".", 1 modules: Writerside.
java.lang.Throwable: Cannot find module "itineraire-touristique" in solution ".".
	at supernova.core.SupernovaStarter$1.lambda$projectOpened$0(SupernovaStarter.java:157)
	at com.intellij.openapi.project.DumbServiceImpl.doUnsafeRunWhenSmart(DumbServiceImpl.java:252)
	at com.intellij.openapi.project.DumbServiceImpl.lambda$doUnsafeRunWhenSmart$2(DumbServiceImpl.java:255)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:838)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:454)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:74)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:1[14](https://github.com/pasglop/itineraire-touristique/actions/runs/5254282841/jobs/9492691486#step:4:15))
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:36)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:779)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:749)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:909)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:756)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$5(IdeEventQueue.java:437)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:436)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:6[15](https://github.com/pasglop/itineraire-touristique/actions/runs/5254282841/jobs/9492691486#step:4:16))
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:434)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:838)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:480)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:1[17](https://github.com/pasglop/itineraire-touristique/actions/runs/5254282841/jobs/9492691486#step:4:18))
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:[92](https://github.com/pasglop/itineraire-touristique/actions/runs/5254282841/jobs/9492691486#step:4:93))
Test existing of  artifact

**Comment by pasglop** [comment]
I tried to add 
          with:
            set-safe-directory: '/github/workspace'

on the Checkout repository step, but does not change anything

**Comment by PHPirates** [comment]
> detected dubious ownership in repository at '/github/workspace'
> Exception in thread "Thread-123" java.lang.NullPointerException: Cannot invoke "java.awt.GraphicsConfiguration.createCompatibleVolatileImage(int, int, int)" because the return value of "javax.swing.JComponent.getGraphicsConfiguration()" is null

These are non-fatal errors, as far as I can see they have no effect.

> java.lang.Throwable: Cannot find module "itineraire-touristique" in solution ".".

This is your actual error failing the build.

**Comment by lananovikova10** [comment]
Hi!

> Open solution: ".", 1 modules: Writerside.
> java.lang.Throwable: Cannot find module "itineraire-touristique" in solution ".".

The issue is that the module is called Writerside, not itineraire-touristique. We've created an issue in our YouTrack here https://youtrack.jetbrains.com/issue/WRS-2350/Cannot-build-documentation-safe-directory-issue, and we will consider how we can make the build log less cluttered so that it would be easier to find a root cause.
